sudo: false
dist: xenial
language: python
cache: pip
python: 3.7
matrix:
  fast_finish: true
addons:
  sonarcloud:
    organization: openexo
install: pip install -r requirements_test.txt
script:
  - tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  twine_version: 1.13.0
  user: __token__
  password:
    secure: eKLDsa8D2rrFCVF81I8EyxXcGcQIpiw3rBMpgIEYjK/Nxah2nMPNfp5wg3/L0yaLbncnNH5F5E8d5ZT/i1OgH+I8bWO/0gdZPkTGzuvrmj1/P9aZ/GkRQEGWdbOvJSrctRhWc7PmoaC4pHqDQFO/6AGAvbigAY9ArWZ07pSAGwGDwFXE6kacTlAYrxadG7fO3u1J9dnt54dOFCOkPUVTM0ufSvJjBQa7FfmE5uwwCSeJZ4elYTzFNg9HwPMWbFs3e3PnIUZj2c91rOLl94Ld3b67ncYtarKoZE+UMGIVQvC9RZvy+5NF2/AegUhuAMS8OQ/nJFOlF8JBEWILv03GUklDRn9X4xVHCUHqkEHSJ5lZ0WSAcePmRROX/xx1E7JS9gNScyuSu63TgzMyqECJe8fUD/wEWnSN+k7f7iaElKRhNv8R5VaQTnaS4v+aHCmZcTYSLW2ayzCSr1Ptjsz7bz5vxwGOjlo6sqRvUk8cNIOJTNCTvsRo3uTi0TWGzhpwuJ8ZVF53wDg81b0kh+dCXVJzHo6I79KOI+dS3syz6E3zI1rKdBv9rSIr6f4kJeV9QnHS/xHAM0/VrgUUugGrnq6CpJF5Y6BhE0MCX90yxFKJlfIPwh7cx4MeTLHcmcoRMI+rqxiKyQgcSTt38vk5P/zvxe93pYwJpNXqWO9l2/c=
  on:
    tags: true
    repo: exolever/django-accredible
    python: 3.7
after_success:
  - codecov
