# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20181017_1424'),
    ]

    operations = [
    ]
